"""
Simple, Easy-to-Understand Streamlit UI for PS-06 (Steps 1 to 4: Up to RAG)
---------------------------------------------------------------------------
Uses 100% Masked Original PS-06 Data:
- Tab 1: Step 1 (Load & Mask Data)
- Tab 2: Step 2 (Correlate Alarms & Find Probable Root Cause)
- Tab 3: Step 3 (Check KPIs Against Normal Baseline)
- Tab 4: Step 4 (RAG Runbook Search & Section Citations)
"""

import json
import os
import pandas as pd
import streamlit as st

from step4_rag import retrieve_runbook_guidance

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

st.set_page_config(
    page_title="PS-06 | Masked Network Triage & RAG (Steps 1 to 4)",
    page_icon="📡",
    layout="wide",
)

# Load outputs generated by Steps 1, 2, 3
with open(os.path.join(BASE_DIR, "data", "alarms", "masked_alarms.json"), "r", encoding="utf-8") as f:
    masked_alarms = json.load(f)

with open(os.path.join(BASE_DIR, "data", "topology", "masked_topology.json"), "r", encoding="utf-8") as f:
    masked_topology = json.load(f)

with open(os.path.join(BASE_DIR, "data", "alarms", "correlated_incidents.json"), "r", encoding="utf-8") as f:
    corr_data = json.load(f)

with open(os.path.join(BASE_DIR, "data", "kpis", "kpi_anomalies.json"), "r", encoding="utf-8") as f:
    kpi_data = json.load(f)

df_kpis = pd.read_csv(os.path.join(BASE_DIR, "data", "kpis", "masked_kpis.csv"))
incidents = corr_data["incidents"]

# Header
st.title("📡 PS-06: Network Health-Check & Alarm Triage (Steps 1 to 4)")
st.caption("Built Step-by-Step on Original Masked PS-06 Data (`step1_load_and_mask.py` → `step2_correlate.py` → `step3_kpi_check.py` → `step4_rag.py`)")

c1, c2, c3, c4 = st.columns(4)
c1.metric("Step 1: Masked Alarms", len(masked_alarms))
c2.metric("Step 2: Correlated Incidents", len(incidents))
c3.metric("Step 3: KPI Anomalies", kpi_data["total_anomalies"])
c4.metric("Step 4: Masked Runbooks", "3 Runbooks (CPF, UPF-1, UPF-2)")

st.divider()

tab1, tab2, tab3, tab4 = st.tabs([
    "Step 1: 📂 Load & Mask Data",
    "Step 2: 🔗 Correlate & Root Cause",
    "Step 3: 📈 Check KPIs (Baseline)",
    "Step 4: 📚 RAG (Runbook Citations)",
])

# ==============================================================================
# TAB 1: STEP 1 — LOAD & MASK DATA
# ==============================================================================
with tab1:
    st.header("Step 1: Original PS-06 Data Loaded & Masked (`step1_load_and_mask.py`)")
    st.write(
        "All confidential identifiers (`INVI...` hostnames, `VIL`/`Vodafone`/`Idea`, `Agra`, `UWAGRS_*` peers, "
        "and all IPv4/IPv6 addresses) are masked before saving to `data/`."
    )

    col_left, col_right = st.columns([1, 1.4])
    with col_left:
        st.subheader("1A. Masked Topology Nodes (4 Nodes)")
        st.dataframe(pd.DataFrame(masked_topology["nodes"]), use_container_width=True, hide_index=True)

        st.subheader("1B. Masked Topology Links (6 Links)")
        st.dataframe(pd.DataFrame(masked_topology["links"]), use_container_width=True, hide_index=True)

    with col_right:
        st.subheader("1C. 500 Masked Alarms (`data/alarms/masked_alarms.json`)")
        st.dataframe(
            pd.DataFrame(masked_alarms)[
                ["alarm_id", "timestamp", "node", "severity", "alarm_code", "alarm_type", "resource", "details"]
            ],
            use_container_width=True,
            hide_index=True,
            height=420,
        )

# ==============================================================================
# TAB 2: STEP 2 — CORRELATE & FIND PROBABLE ROOT CAUSE
# ==============================================================================
with tab2:
    st.header("Step 2: Correlate Alarms & Rank Probable Root Cause (`step2_correlate.py`)")
    st.write(
        f"Out of **{corr_data['total_raw_alarms']} masked alarms**, Step 2 filtered out "
        f"**{corr_data['filtered_noise_count']} routine accounting rollover logs** (`LOGGER #2008/#2009`) "
        f"and grouped the remaining **{corr_data['fault_alarms_count']} fault alarms** into "
        f"**{corr_data['incident_count']} Incidents**."
    )

    inc_map = {f"{i['incident_id']} — {i['title']} ({i['total_alarms']} alarms)": i for i in incidents}
    selected_inc_label = st.selectbox("Select an Incident to Inspect:", list(inc_map.keys()))
    inc = inc_map[selected_inc_label]

    st.success(
        f"🎯 **Probable Root Cause**: `{inc['probable_root_alarm_code']}` (`{inc['probable_root_alarm_type']}`) "
        f"on Node **`{inc['probable_root_node']}`**  |  **Layer**: `{inc['probable_root_layer']}`  |  "
        f"**Confidence**: `{int(inc['confidence_score']*100)}%`"
    )
    st.info(inc["reasoning_summary"])

    col_r1, col_r2 = st.columns(2)
    with col_r1:
        st.subheader("🏆 Probable Root Cause Ranking")
        rank_df = pd.DataFrame(inc["root_ranking"])[
            ["node", "alarm_code", "alarm_type", "layer", "severity", "score", "explanation"]
        ]
        st.dataframe(rank_df, use_container_width=True, hide_index=True)

    with col_r2:
        st.subheader(f"📋 Correlated Symptom Alarms ({inc['total_alarms']} Alarms)")
        sym_df = pd.DataFrame(inc["symptom_alarms"])[
            ["alarm_id", "timestamp", "node", "severity", "alarm_code", "alarm_type", "resource"]
        ]
        st.dataframe(sym_df, use_container_width=True, hide_index=True, height=280)

# ==============================================================================
# TAB 3: STEP 3 — CHECK KPIS AGAINST NORMAL BASELINE
# ==============================================================================
with tab3:
    st.header("Step 3: Check KPIs Against Normal Baseline (`step3_kpi_check.py`)")
    st.write(
        "Compares the **25 3GPP XML KPI intervals** (`data/kpis/masked_kpis.csv`) against each node's "
        "**Normal Baseline Median** and flags spikes/drops with $|Z\\text{-score}| \\ge 2.0$."
    )

    st.subheader(f"🚨 Detected KPI Anomalies ({kpi_data['total_anomalies']} Total Across All 3 Nodes)")
    st.dataframe(pd.DataFrame(kpi_data["anomalies"]), use_container_width=True, hide_index=True, height=260)

    st.divider()
    st.subheader("📊 Interactive KPI Time-Series Chart")
    kc1, kc2 = st.columns([1, 2])
    with kc1:
        node_choice = st.selectbox("Select Masked Node:", kpi_data["nodes_checked"])
        metric_cols = [c for c in df_kpis.columns if c not in ("node", "timestamp")]
        metric_choice = st.selectbox("Select KPI Metric:", metric_cols)
        b_info = kpi_data["baselines"][node_choice][metric_choice]
        st.metric("Normal Baseline (Median)", b_info["baseline_median"])
        st.metric("Peak / Max Observed", b_info["max"])

    with kc2:
        node_sub = df_kpis[df_kpis["node"] == node_choice][["timestamp", metric_choice]].set_index("timestamp")
        st.line_chart(node_sub)

# ==============================================================================
# TAB 4: STEP 4 — RAG RUNBOOK SEARCH & SECTION CITATIONS
# ==============================================================================
with tab4:
    st.header("Step 4: RAG Runbook Search & Citations (`step4_rag.py`)")
    st.write(
        "Looks up the Probable Root Cause in the **3 Masked Runbooks** (`RB_CPF_Masked.md`, `RB_UPF01_Masked.md`, `RB_UPF02_Masked.md`) "
        "and returns the exact section citation and CLI health-check commands."
    )

    rag_result = retrieve_runbook_guidance(
        alarm_code=inc["probable_root_alarm_code"],
        alarm_type=inc["probable_root_alarm_type"],
        node=inc["probable_root_node"],
    )

    st.subheader(f"📌 RAG Result for Incident `{inc['incident_id']}` (`{inc['probable_root_alarm_code']}` on `{inc['probable_root_node']}`)")
    if rag_result["status"] == "found":
        st.markdown(f"**Exact Runbook Citation**: `{rag_result['citation']}`")
        rc1, rc2 = st.columns(2)
        with rc1:
            st.markdown("**Recommended CLI Commands to Run:**")
            for cmd in rag_result["recommended_commands"]:
                st.code(cmd, language="bash")
            if rag_result["past_incident"]:
                pi = rag_result["past_incident"]
                st.markdown(f"**Matching Past Incident (`{pi['case_id']}`)**:")
                st.write(f"- **Problem:** {pi['problem']}")
                st.write(f"- **Resolution:** {pi['resolution']}")
        with rc2:
            st.markdown("**Cited Runbook Section Content:**")
            st.info(rag_result["section_content"])
    else:
        st.error(rag_result["message"])

    st.divider()
    st.subheader("🔍 Test Any Alarm Code in RAG (Verify 'not found' Rule)")
    t1, t2, t3 = st.columns(3)
    custom_code = t1.text_input("Alarm Code", value="VRTR #2061", help="Try typing 'UNKNOWN #999' to test 'not found'")
    custom_type = t2.text_input("Alarm Type (Optional)", value="BFD_SESSION_DOWN_NBR_SIGNAL")
    custom_node = t3.text_input("Node", value="MASKED-UPF-01")

    if st.button("Search Masked Runbooks"):
        custom_res = retrieve_runbook_guidance(custom_code, custom_type, custom_node)
        if custom_res["status"] == "not found":
            st.error(f"Result: **not found** — `{custom_res['message']}`")
        else:
            st.success(f"Found! Citation: `{custom_res['citation']}`")
            st.code("\n".join(custom_res["recommended_commands"]), language="bash")
